---
title: "test_flashdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width =6, fig.height = 6, fig.align  = "centre"  )
library(arm)
library(readxl)
library(readr)
library(tidyverse)
library(data.table)
library(gridExtra)
library(knitr)
library(pscl)
library(rworldmap)
library(corrplot)
library(car)
library(nlme)
library(lme4)
library(blme)
library(dplyr)
library(astsa)


monthdata <- read_excel("ma678midppj.xlsx")
yeardata <- read_excel("ma678midpj2.xlsx")

monthdata_new <- read_excel("monthly.xlsx")
yeardata_new <- read_excel("yearly.xlsx")
yeardata_new1 <- yeardata_new%>%filter(Year!=1979)
datasorted <- yeardata_new1[rep(seq_len(nrow(yeardata_new1)), each=1),]
datasorted <- datasorted[rep(seq_len(nrow(datasorted)), each=12),]
datasorted <- datasorted[-seq(2809,2832,1),] #remove data of 1980-1081India

##month data
monthdata_new <- monthdata_new%>%filter(Country!="Mauritius"&Country!="South Africa")

#cbind year data&month data
datafinal <- cbind(monthdata_new,datasorted[,-c(1,2,3)])


#exchange rate adjsutment
datafinal[datafinal$Country=="Japan",]$Exports=(datafinal[datafinal$Country=="Japan",]$Exports)/100  #HML TO ML
datafinal[datafinal$Country=="India",]$Exports=(datafinal[datafinal$Country=="India",]$Exports)/100 #HML TO ML
datafinal[datafinal$Country=="United Kingdom",]$Exports=(datafinal[datafinal$Country=="United Kingdom",]$Exports)*1.27 #pound to usd

```

Column {data-width=650}
-----------------------------------------------------------------------

### Export of each country

```{r}
library(ggsignif)

ggplot(datafinal, aes(x = Year, y = Exports, fill = datafinal$Country)) +
      geom_bar(stat = "identity") + scale_fill_brewer(palette="Set3")+    theme_minimal() + 
    geom_signif(comparisons=list(c("2008", "2009")), annotations="***",
              y_position = 9000000, tip_length = 2, vjust=4)+
      ggtitle("Exports")

export_removejpnind <- datafinal%>%filter(Country!="Japan"&Country!="India")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

ggplot(datafinal, aes(x = datafinal$`Unemployment rate`, y = Exports, color = datafinal$Country)) +
      geom_point(stat = "identity", position = position_dodge()) +   theme_minimal() + 
      geom_smooth()+
      ggtitle("Unemployment rate versus exports") + theme_classic() +ylim(0,200000)

```


### Correlation

```{r,fig.width=10,fig.height=10}
colnames(datafinal) <- c("Country","Code","Year","Month","GDP","CPI","r_deposit","r_business","employment","unemployment","ecogrowth","Exports","FDI","ExchangeDeposit","Gov_expenditure","Prod","Inflation","Exchange","RetailSale","BusinessConfidenceSurvey","Reserves","Tax_internation","Tax_corporate","Imports","Tax_indirect","Remittances","Ecoforecast","Inflationforecast","Unemplymentforecast","Law","Gov_effectiveness","Political_stability")

require('RColorBrewer')
  t <- data.frame("Deposit interest rate"=datafinal$r_deposit, "CPI"=datafinal$CPI, "Unemplyment"=datafinal$unemployment, "Inflation"=datafinal$Inflation,"Exchange Rate"=datafinal$Exchange, "Business confidence survey"=datafinal$BusinessConfidenceSurvey,"Inflation forecast"=datafinal$Inflationforecast, "Foreign Exchange Reserve"=datafinal$ExchangeDeposit)
t <- na.omit(t)
M<-cor(t,use = "pair")

#correlation plot
col <- colorRampPalette(c('#2F2C62', '#42399B', '#4A52A7', '#59AFEA', '#7BCEB8', '#A7DA64',
            '#EFF121', '#F5952D', '#E93131', '#D70131', '#D70131'))
corrplot(M, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```

